# Site settings
author: Niko G.
title: “Data really powers everything that we do.” 
header-img: img/home-bg.png
email: ganevniko@hotmail.com
copyright_name: Niko G.
description: > # this means to ignore newlines until "baseurl:"

  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ganevniko

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
